# fly.toml app configuration file generated for memo-sync on 2026-02-04T01:06:07-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'memo-sync'
primary_region = 'nrt'

[build]

[env]
  GIN_MODE = 'release'
  LOG_LEVEL = 'info'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[metrics]]
  port = 8080
  path = '/metrics'
